Prepare 5.2.2-r5

diff --git a/apk/renewal-hooks.dist/deploy/02-lighthttpd b/apk/renewal-hooks.dist/deploy/02-lighthttpd
--- a/apk/renewal-hooks.dist/deploy/02-lighthttpd
+++ b/apk/renewal-hooks.dist/deploy/02-lighthttpd
@@ -1,5 +1,7 @@
 #!/usr/bin/env sh
 
+WHAT=lighthttpd
+
 if test "x${RENEWED_LINEAGE}" == "x"; then
    RENEWED_LINEAGE=/etc/letsencrypt/live/$(certbot certificates 2>/dev/null | grep "Certificate Name:" | head -1 | cut -d":" -f2 | xargs)
    echo RENEWED_LINEAGE=$RENEWED_LINEAGE
@@ -8,24 +10,30 @@ fi
 # We need openssl
 export PATH=$PATH:/usr/builtin/bin/
 
+function logger() {
+  echo "${@}" >&2
+  syslog --log 0 --level 0 --user SYSTEM --event "${@}"
+}
+
 # If issuer is Asustor, then our certificates are not installed
 if test "x${RENEWED_LINEAGE}" == "x"; then
-  echo "Skipping, RENEWED_LINEAGE is not set" >&2
+  logger "[Certbot] Skipping ${WHAT} restart, RENEWED_LINEAGE is not set"
   exit 1
 elif openssl x509 -noout -text -in  /usr/builtin/etc/certificate/ssl.crt | grep Issuer | grep -q Asustor; then
-  echo "Certificate is from Asustor, not restarting lighthttpd" >&2
+  logger "[Certbot] Certificate is from Asustor, not restarting ${WHAT}"
   exit 1
 elif test ! -f "${RENEWED_LINEAGE}"/cert.pem; then
-  echo "Certificates not found in ${RENEWED_LINEAGE}, not restarting lighthttpd" >&2
+  logger "[Certbot] Certificates not found in ${RENEWED_LINEAGE}, not restarting ${WHAT}"
   exit 1
 elif openssl x509 -noout -text -in "${RENEWED_LINEAGE}"/cert.pem | grep Issuer | grep -q "Let's Encrypt"; then
   true
 else
-  echo "Certificate is neither from Asustor nor Let's Encrypt, not restarting lighthttpd" >&2
+  logger "[Certbot] Certificate is neither from Asustor nor Let's Encrypt, not restarting ${WHAT}"
   exit 1
 fi
 
 if test -f /etc/init.d/S41lighttpd; then
+  logger "[Certbot] Restarting ${WHAT}..."
   /etc/init.d/S41lighttpd restart
 fi
 exit 0
